### PR TITLE
Work around installation issues for v1.0.22

### PR DESCRIPTION
**Pull request by mrakitin**
See https://github.com/hamano/pysmbc/issues/53 for details.

### CODE REVIEW

**Comment by hamano** [comment]
Thank you for your investigation.
The smbclient and libsmbclient are independent packages.
pysmbc depends on libsmbclient but not smbclient.
I don't want to use smbclient command.
Is there another way to get the libsmbclient version on CentOS?

**Comment by mrakitin** [comment]
I see, that makes sense to depend on less libraries/packages.

By the way, what's the oldest supported version of `libsmbclient`? I found that there is a `samba4` package for older CentOS versions (v6), but it does not seem to provide the `libsmblient` library. I guess we need the header files, right?

**Comment by mrakitin** [comment]
`rpm -qa` can show installed packages' versions, but it becomes distro-specific...

**Comment by hamano** [comment]
see #53

**Pull request closed without merging**
